#!/bin/bash
# configure-project --- Configure repository dependencies for building and tests.
set -e

cd $PROJ_DIR

echo "Installing dependencies ..."
npm install

echo -e "\nSelect a Firebase application name where tests will be executed."
echo "WARNING: ALL DATA IN THIS DATABASE WILL BE REMOVED BY RUNNING TESTS."
echo "         Please create an application specifically for testing."
echo "         DO NOT use the name of your production database!!!"

ensure-secret.py auth-secrets.js

# Show outdated modules
npm outdated
