#!/bin/bash
# run-tests --- Run unit tests in mocha - passing commandline options.

set -e

cd $PROJ_DIR
gulp clean
if gulp lint build; then
    mocha lib/test --ui tdd --require "source-map-support/register" "$@"
fi
